def create_datacard(year, mass_range, lepton_flavor):
    filename = 'datacard_{}_{}_{}.txt'.format(year, lepton_flavor, mass_range)
    filepath = 'combine_input/dY_{}_{}_{}.root'.format(year, lepton_flavor, mass_range)
    
    with open(filename, 'w') as file:
        file.write("imax 1 number of bins\n")
        file.write("jmax 6 number of processes minus 1\n")
        file.write("kmax * number of nuisance parameters\n")
        file.write("----------------------------------------------------------------------------------------------------------------------------------\n")
        file.write("shapes data_obs     {}_{}_{}       {} $PROCESS\n".format(lepton_flavor, year, mass_range, filepath))
        file.write("shapes *            *       {} $PROCESS $PROCESS_$SYSTEMATIC\n".format(filepath))
        file.write("----------------------------------------------------------------------------------------------------------------------------------\n")
        file.write("bin          {}_{}_{}\n".format(lepton_flavor, year, mass_range))
        file.write("observation  -1\n")
        file.write("----------------------------------------------------------------------------------------------------------------------------------\n")
        file.write("bin                     {}_{}_{}     {}_{}_{}     {}_{}_{}     {}_{}_{}     {}_{}_{}     {}_{}_{}     {}_{}_{}\n".format(lepton_flavor, year, mass_range, lepton_flavor, year, mass_range, lepton_flavor, year, mass_range, lepton_flavor, year, mass_range, lepton_flavor, year, mass_range, lepton_flavor, year, mass_range, lepton_flavor, year, mass_range))
        file.write("process                 TTbar_1               TTbar_2               WJets                 QCD                   DY                    Diboson               ST\n")
        file.write("process                 -1                    0                     1                     2                     3                     4                     5\n")
        file.write("rate                    -1                    -1                    -1                    -1                    -1                    -1                    -1\n")
        file.write("----------------------------------------------------------------------------------------------------------------------------------\n")
        
        # Systematics
        electron_systematics = [
            "lumi_corr_161718    lnN     1.02      1.02      1.02      1.02      1.02      1.02      1.02",
            "lumi_corr_1718      lnN     1.002     1.002     1.002     1.002     1.002     1.002     1.002",
            "lumi_uncorr_18      lnN     1.015     1.015     1.015     1.015     1.015     1.015     1.015",
            "lumi_corr_161718    lnN     1.02      1.02      1.02      1.02      1.02      1.02      1.02",
            "lumi_corr_1718      lnN     1.002     1.002     1.002     1.002     1.002     1.002     1.002",
            "lumi_uncorr_18      lnN     1.015     1.015     1.015     1.015     1.015     1.015     1.015",
            "lumi_uncorr_17      lnN     -         -         -         -         -         -         - ",            
            "lumi_uncorr_16      lnN     -         -         -         -         -         -         - ",
            "lumi                lnN     1.016     1.016     1.016     1.016     1.016     1.016     1.016",
            "pu                  shape   1         1         1         1         1         1         1",
            "prefiringWeight     shape   1         1         1         1         1         1         1",
            "electronID          shape   1         1         1         1         1         1         1",
            "electronTrigger     shape   1         1         1         1         1         1         1",
            "electronReco        shape   1         1         1         1         1         1         1",
            "isr                 shape   1         1         1         1         1         1         1",
            "fsr                 shape   1         1         1         1         1         1         1",
            "btagCferr1          shape   1         1         1         1         1         1         1",
            "btagCferr2          shape   1         1         1         1         1         1         1",
            "btagHf              shape   1         1         1         1         1         1         1",
            "btagHfstats1        shape   1         1         1         1         1         1         1",
            "btagHfstats2        shape   1         1         1         1         1         1         1",
            "btagLf              shape   1         1         1         1         1         1         1",
            "btagLfstats1        shape   1         1         1         1         1         1         1",
            "btagLfstats2        shape   1         1         1         1         1         1         1",
            "ttagCorr            shape   1         1         1         1         1         1         1",
            "ttagUncorr          shape   1         1         1         1         1         1         1",
            "tmistag             shape   1         1         1         1         1         1         1",
            "murmuf              shape   1         1         1         1         1         1         1",
            "PDF_1               shape   1         1         1         1         1         1         1",
            "PDF_2               shape   1         1         1         1         1         1         1",
            "PDF_3               shape   1         1         1         1         1         1         1",
            "PDF_4               shape   1         1         1         1         1         1         1",
            "PDF_5               shape   1         1         1         1         1         1         1",
            "PDF_6               shape   1         1         1         1         1         1         1",
            "PDF_7               shape   1         1         1         1         1         1         1",
            "PDF_8               shape   1         1         1         1         1         1         1",
            "PDF_9               shape   1         1         1         1         1         1         1",
            "PDF_10              shape   1         1         1         1         1         1         1",
            "PDF_11              shape   1         1         1         1         1         1         1",
            "PDF_12              shape   1         1         1         1         1         1         1",
            "PDF_13              shape   1         1         1         1         1         1         1",
            "PDF_14              shape   1         1         1         1         1         1         1",
            "PDF_15              shape   1         1         1         1         1         1         1",
            "PDF_16              shape   1         1         1         1         1         1         1",
            "PDF_17              shape   1         1         1         1         1         1         1",
            "PDF_18              shape   1         1         1         1         1         1         1",
            "PDF_19              shape   1         1         1         1         1         1         1",
            "PDF_20              shape   1         1         1         1         1         1         1",
            "PDF_21              shape   1         1         1         1         1         1         1",
            "PDF_22              shape   1         1         1         1         1         1         1",
            "PDF_23              shape   1         1         1         1         1         1         1",
            "PDF_24              shape   1         1         1         1         1         1         1",
            "PDF_25              shape   1         1         1         1         1         1         1",
            "PDF_26              shape   1         1         1         1         1         1         1",
            "PDF_27              shape   1         1         1         1         1         1         1",
            "PDF_28              shape   1         1         1         1         1         1         1",
            "PDF_29              shape   1         1         1         1         1         1         1",
            "PDF_30              shape   1         1         1         1         1         1         1",
            "PDF_31              shape   1         1         1         1         1         1         1",
            "PDF_32              shape   1         1         1         1         1         1         1",
            "PDF_33              shape   1         1         1         1         1         1         1",
            "PDF_34              shape   1         1         1         1         1         1         1",
            "PDF_35              shape   1         1         1         1         1         1         1",
            "PDF_36              shape   1         1         1         1         1         1         1",
            "PDF_37              shape   1         1         1         1         1         1         1",
            "PDF_38              shape   1         1         1         1         1         1         1",
            "PDF_39              shape   1         1         1         1         1         1         1",
            "PDF_40              shape   1         1         1         1         1         1         1",
            "PDF_41              shape   1         1         1         1         1         1         1",
            "PDF_42              shape   1         1         1         1         1         1         1",
            "PDF_43              shape   1         1         1         1         1         1         1",
            "PDF_44              shape   1         1         1         1         1         1         1",
            "PDF_45              shape   1         1         1         1         1         1         1",
            "PDF_46              shape   1         1         1         1         1         1         1",
            "PDF_47              shape   1         1         1         1         1         1         1",
            "PDF_48              shape   1         1         1         1         1         1         1",
            "PDF_49              shape   1         1         1         1         1         1         1",
            "PDF_50              shape   1         1         1         1         1         1         1",
            "PDF_51              shape   1         1         1         1         1         1         1",
            "PDF_52              shape   1         1         1         1         1         1         1",
            "PDF_53              shape   1         1         1         1         1         1         1",
            "PDF_54              shape   1         1         1         1         1         1         1",
            "PDF_55              shape   1         1         1         1         1         1         1",
            "PDF_56              shape   1         1         1         1         1         1         1",
            "PDF_57              shape   1         1         1         1         1         1         1",
            "PDF_58              shape   1         1         1         1         1         1         1",
            "PDF_59              shape   1         1         1         1         1         1         1",
            "PDF_60              shape   1         1         1         1         1         1         1",
            "PDF_61              shape   1         1         1         1         1         1         1",
            "PDF_62              shape   1         1         1         1         1         1         1",
            "PDF_63              shape   1         1         1         1         1         1         1",
            "PDF_64              shape   1         1         1         1         1         1         1",
            "PDF_65              shape   1         1         1         1         1         1         1",
            "PDF_66              shape   1         1         1         1         1         1         1",
            "PDF_67              shape   1         1         1         1         1         1         1",
            "PDF_68              shape   1         1         1         1         1         1         1",
            "PDF_69              shape   1         1         1         1         1         1         1",
            "PDF_70              shape   1         1         1         1         1         1         1",
            "PDF_71              shape   1         1         1         1         1         1         1",
            "PDF_72              shape   1         1         1         1         1         1         1",
            "PDF_73              shape   1         1         1         1         1         1         1",
            "PDF_74              shape   1         1         1         1         1         1         1",
            "PDF_75              shape   1         1         1         1         1         1         1",
            "PDF_76              shape   1         1         1         1         1         1         1",
            "PDF_77              shape   1         1         1         1         1         1         1",
            "PDF_78              shape   1         1         1         1         1         1         1",
            "PDF_79              shape   1         1         1         1         1         1         1",
            "PDF_80              shape   1         1         1         1         1         1         1",
            "PDF_81              shape   1         1         1         1         1         1         1",
            "PDF_82              shape   1         1         1         1         1         1         1",
            "PDF_83              shape   1         1         1         1         1         1         1",
            "PDF_84              shape   1         1         1         1         1         1         1",
            "PDF_85              shape   1         1         1         1         1         1         1",
            "PDF_86              shape   1         1         1         1         1         1         1",
            "PDF_87              shape   1         1         1         1         1         1         1",
            "PDF_88              shape   1         1         1         1         1         1         1",
            "PDF_89              shape   1         1         1         1         1         1         1",
            "PDF_90              shape   1         1         1         1         1         1         1",
            "PDF_91              shape   1         1         1         1         1         1         1",
            "PDF_92              shape   1         1         1         1         1         1         1",
            "PDF_93              shape   1         1         1         1         1         1         1",
            "PDF_94              shape   1         1         1         1         1         1         1",
            "PDF_95              shape   1         1         1         1         1         1         1",
            "PDF_96              shape   1         1         1         1         1         1         1",
            "PDF_97              shape   1         1         1         1         1         1         1",
            "PDF_98              shape   1         1         1         1         1         1         1",
            "PDF_99              shape   1         1         1         1         1         1         1",
            "PDF_100             shape   1         1         1         1         1         1         1",
            "jer                 shape   1         1         1         1         1         1         1",
            "jec                 shape   1         1         1         1         1         1         1",
            "TTbar_1_norm        lnN     1.05      -         -         -         -         -         - ",     
            "TTbar_2_norm        lnN     -         1.05      -         -         -         -         -",
            "Wjets_norm          lnN     -         -         1.3       -         -         -         -",
            "QCD_norm            lnN     -         -         -         1.5       -         -         -",
            "DY_norm             lnN     -         -         -         -         1.3       -         -",
            "Diboson_norm        lnN     -         -         -         -         -         1.3      -",
            "ST_norm             lnN     -         -         -         -         -         -         1.3"
        ]
        
        muon_systematics = [
            "lumi_corr_161718    lnN     1.02      1.02      1.02      1.02      1.02      1.02      1.02",
            "lumi_corr_1718      lnN     1.002     1.002     1.002     1.002     1.002     1.002     1.002",
            "lumi_uncorr_18      lnN     1.015     1.015     1.015     1.015     1.015     1.015     1.015",
            "lumi_corr_161718    lnN     1.02      1.02      1.02      1.02      1.02      1.02      1.02",
            "lumi_corr_1718      lnN     1.002     1.002     1.002     1.002     1.002     1.002     1.002",
            "lumi_uncorr_18      lnN     1.015     1.015     1.015     1.015     1.015     1.015     1.015",
            "lumi_uncorr_17      lnN     -         -         -         -         -         -         - ",            
            "lumi_uncorr_16      lnN     -         -         -         -         -         -         - ",
            "lumi                lnN     1.016     1.016     1.016     1.016     1.016     1.016     1.016",
            "pu                  shape   1         1         1         1         1         1         1",
            "muonReco            shape   1         1         1         1         1         1         1",
            "prefiringWeight     shape   1         1         1         1         1         1         1",
            "muonID              shape   1         1         1         1         1         1         1",
            "muonIso             shape   1         1         1         1         1         1         1",
            "muonTrigger         shape   1         1         1         1         1         1         1",
            "isr                 shape   1         1         1         1         1         1         1",
            "fsr                 shape   1         1         1         1         1         1         1",
            "btagCferr1          shape   1         1         1         1         1         1         1",
            "btagCferr2          shape   1         1         1         1         1         1         1",
            "btagHf              shape   1         1         1         1         1         1         1",
            "btagHfstats1        shape   1         1         1         1         1         1         1",
            "btagHfstats2        shape   1         1         1         1         1         1         1",
            "btagLf              shape   1         1         1         1         1         1         1",
            "btagLfstats1        shape   1         1         1         1         1         1         1",
            "btagLfstats2        shape   1         1         1         1         1         1         1",
            "ttagCorr            shape   1         1         1         1         1         1         1",
            "ttagUncorr          shape   1         1         1         1         1         1         1",
            "tmistag             shape   1         1         1         1         1         1         1",
            "murmuf              shape   1         1         1         1         1         1         1",
            "PDF_1               shape   1         1         1         1         1         1         1",
            "PDF_2               shape   1         1         1         1         1         1         1",
            "PDF_3               shape   1         1         1         1         1         1         1",
            "PDF_4               shape   1         1         1         1         1         1         1",
            "PDF_5               shape   1         1         1         1         1         1         1",
            "PDF_6               shape   1         1         1         1         1         1         1",
            "PDF_7               shape   1         1         1         1         1         1         1",
            "PDF_8               shape   1         1         1         1         1         1         1",
            "PDF_9               shape   1         1         1         1         1         1         1",
            "PDF_10              shape   1         1         1         1         1         1         1",
            "PDF_11              shape   1         1         1         1         1         1         1",
            "PDF_12              shape   1         1         1         1         1         1         1",
            "PDF_13              shape   1         1         1         1         1         1         1",
            "PDF_14              shape   1         1         1         1         1         1         1",
            "PDF_15              shape   1         1         1         1         1         1         1",
            "PDF_16              shape   1         1         1         1         1         1         1",
            "PDF_17              shape   1         1         1         1         1         1         1",
            "PDF_18              shape   1         1         1         1         1         1         1",
            "PDF_19              shape   1         1         1         1         1         1         1",
            "PDF_20              shape   1         1         1         1         1         1         1",
            "PDF_21              shape   1         1         1         1         1         1         1",
            "PDF_22              shape   1         1         1         1         1         1         1",
            "PDF_23              shape   1         1         1         1         1         1         1",
            "PDF_24              shape   1         1         1         1         1         1         1",
            "PDF_25              shape   1         1         1         1         1         1         1",
            "PDF_26              shape   1         1         1         1         1         1         1",
            "PDF_27              shape   1         1         1         1         1         1         1",
            "PDF_28              shape   1         1         1         1         1         1         1",
            "PDF_29              shape   1         1         1         1         1         1         1",
            "PDF_30              shape   1         1         1         1         1         1         1",
            "PDF_31              shape   1         1         1         1         1         1         1",
            "PDF_32              shape   1         1         1         1         1         1         1",
            "PDF_33              shape   1         1         1         1         1         1         1",
            "PDF_34              shape   1         1         1         1         1         1         1",
            "PDF_35              shape   1         1         1         1         1         1         1",
            "PDF_36              shape   1         1         1         1         1         1         1",
            "PDF_37              shape   1         1         1         1         1         1         1",
            "PDF_38              shape   1         1         1         1         1         1         1",
            "PDF_39              shape   1         1         1         1         1         1         1",
            "PDF_40              shape   1         1         1         1         1         1         1",
            "PDF_41              shape   1         1         1         1         1         1         1",
            "PDF_42              shape   1         1         1         1         1         1         1",
            "PDF_43              shape   1         1         1         1         1         1         1",
            "PDF_44              shape   1         1         1         1         1         1         1",
            "PDF_45              shape   1         1         1         1         1         1         1",
            "PDF_46              shape   1         1         1         1         1         1         1",
            "PDF_47              shape   1         1         1         1         1         1         1",
            "PDF_48              shape   1         1         1         1         1         1         1",
            "PDF_49              shape   1         1         1         1         1         1         1",
            "PDF_50              shape   1         1         1         1         1         1         1",
            "PDF_51              shape   1         1         1         1         1         1         1",
            "PDF_52              shape   1         1         1         1         1         1         1",
            "PDF_53              shape   1         1         1         1         1         1         1",
            "PDF_54              shape   1         1         1         1         1         1         1",
            "PDF_55              shape   1         1         1         1         1         1         1",
            "PDF_56              shape   1         1         1         1         1         1         1",
            "PDF_57              shape   1         1         1         1         1         1         1",
            "PDF_58              shape   1         1         1         1         1         1         1",
            "PDF_59              shape   1         1         1         1         1         1         1",
            "PDF_60              shape   1         1         1         1         1         1         1",
            "PDF_61              shape   1         1         1         1         1         1         1",
            "PDF_62              shape   1         1         1         1         1         1         1",
            "PDF_63              shape   1         1         1         1         1         1         1",
            "PDF_64              shape   1         1         1         1         1         1         1",
            "PDF_65              shape   1         1         1         1         1         1         1",
            "PDF_66              shape   1         1         1         1         1         1         1",
            "PDF_67              shape   1         1         1         1         1         1         1",
            "PDF_68              shape   1         1         1         1         1         1         1",
            "PDF_69              shape   1         1         1         1         1         1         1",
            "PDF_70              shape   1         1         1         1         1         1         1",
            "PDF_71              shape   1         1         1         1         1         1         1",
            "PDF_72              shape   1         1         1         1         1         1         1",
            "PDF_73              shape   1         1         1         1         1         1         1",
            "PDF_74              shape   1         1         1         1         1         1         1",
            "PDF_75              shape   1         1         1         1         1         1         1",
            "PDF_76              shape   1         1         1         1         1         1         1",
            "PDF_77              shape   1         1         1         1         1         1         1",
            "PDF_78              shape   1         1         1         1         1         1         1",
            "PDF_79              shape   1         1         1         1         1         1         1",
            "PDF_80              shape   1         1         1         1         1         1         1",
            "PDF_81              shape   1         1         1         1         1         1         1",
            "PDF_82              shape   1         1         1         1         1         1         1",
            "PDF_83              shape   1         1         1         1         1         1         1",
            "PDF_84              shape   1         1         1         1         1         1         1",
            "PDF_85              shape   1         1         1         1         1         1         1",
            "PDF_86              shape   1         1         1         1         1         1         1",
            "PDF_87              shape   1         1         1         1         1         1         1",
            "PDF_88              shape   1         1         1         1         1         1         1",
            "PDF_89              shape   1         1         1         1         1         1         1",
            "PDF_90              shape   1         1         1         1         1         1         1",
            "PDF_91              shape   1         1         1         1         1         1         1",
            "PDF_92              shape   1         1         1         1         1         1         1",
            "PDF_93              shape   1         1         1         1         1         1         1",
            "PDF_94              shape   1         1         1         1         1         1         1",
            "PDF_95              shape   1         1         1         1         1         1         1",
            "PDF_96              shape   1         1         1         1         1         1         1",
            "PDF_97              shape   1         1         1         1         1         1         1",
            "PDF_98              shape   1         1         1         1         1         1         1",
            "PDF_99              shape   1         1         1         1         1         1         1",
            "PDF_100             shape   1         1         1         1         1         1         1",
            "jer                 shape   1         1         1         1         1         1         1",
            "jec                 shape   1         1         1         1         1         1         1",
            "TTbar_1_norm        lnN     1.05      -         -         -         -         -         - ",     
            "TTbar_2_norm        lnN     -         1.05      -         -         -         -         -",
            "Wjets_norm          lnN     -         -         1.3       -         -         -         -",
            "QCD_norm            lnN     -         -         -         1.5       -         -         -",
            "DY_norm             lnN     -         -         -         -         1.3       -         -",
            "Diboson_norm        lnN     -         -         -         -         -         1.3      -",
            "ST_norm             lnN     -         -         -         -         -         -         1.3"
        ]

        systematics = muon_systematics if lepton_flavor == "muon" else electron_systematics
        
        for syst in systematics:
            file.write(syst + '\n')

        file.close()

# years = ["UL18", "UL17", "preUL16", "postUL16"]
years = ["UL18"]
mass_ranges = ["0_500", "500_750", "750_1000", "1000_1500", "1500Inf"]
lepton_flavors = ["electron", "muon"]
lepton_flavors = ["electron"]

for year in years:
    for mass_range in mass_ranges:
        for lepton_flavor in lepton_flavors:
            create_datacard(year, mass_range, lepton_flavor)
